### ISSUE TITLE
Declare the job per thread ratio as a class member

### ISSUE THREAD

**Issue by jhlegarreta** [rdebroiz/ITKTBBImageToImageFilter#10]
I'm wondering why the `JOB_PER_THREAD_RATIO` was not declared as a class ivar instead, and be initialized to its default value in the constructor.

I do not see anything wrong with having it as a class ivar, with its corresponding Get/Set methods, and incorporating it to the list of printed variables in `PrintSelf`.

**Comment by rdebroiz** [comment]
We don't want to complicate things, this is used as an empirical heuristic  that should not change during the filter life. We think that users shouldn't be able to interact with it.

what i can do is make it a static class member and print the value in the `PrintSelf`

**Comment by rdebroiz** [comment]
See 0d8dc2114344ba5b77fa199cd6227d45b76fc66e

**Comment by jhlegarreta** [comment]
As per ITK's coding guidelines [1], constants using defines are forbidden.

If users shall not change its value, leaving out the `SetMacro` is enough. So there is nothing wrong with that.

A vast amount of ITK member values are also initialized to some value that was empirically found to yield reasonable results for most cases.

The solution you propose is reasonable at first sight. So thanks for addressing this !

[1] https://itk.org/Wiki/ITK/Tutorials/DOs_and_DONTs#DO_NOT_2
