### ISSUE TITLE
Add the ITK copyright notice to files

### ISSUE THREAD

**Issue by jhlegarreta** [rdebroiz/ITKTBBImageToImageFilter#2]
If this is intended to be added as a remote module to ITK, it would be nice if the ITK copyright notice was added to the files.

**Comment by rdebroiz** [comment]
Is there a tool in ITK to add the right one automatically, or should I just copy it from a random file in ITK?

**Comment by jhlegarreta** [comment]
Taking it from one of the files in ITK should be fine. The official license notice is at the end of the file in
https://github.com/InsightSoftwareConsortium/ITK/blob/master/LICENSE
See the _APPENDIX_ section.

**Comment by jhlegarreta** [comment]
Done in commit 2ce65919adcc7ad60efde820bbb2e859008da687.
