### ISSUE TITLE
Follow ITK coding guidelines

### ISSUE THREAD

**Issue by jhlegarreta** [rdebroiz/ITKTBBImageToImageFilter#3]
Awesome. Thanks for contributing to ITK.

In the ITK wiki [1] you may find coding guidelines.

After a quick look, in order to improve readability and ensure consistency across the toolkit, please:

- ITK uses two-space indentation. Please, adapt your files.
- The flow control statements braces are indented; their contents are indented only once (i.e. aligned with the brackets).
- The method documentation is placed in the class header file.

This
```
If an imaging filter can be implemented as a TBB multithreaded algorithm,
     *          the filter will provide an implementation of TBBGenerateData().
     *          This superclass will automatically split the output image into a number of pieces,
     *          spawn multiple threads, and call TBBGenerateData() in each thread.
     *          Prior to spawning threads, the BeforeThreadedGenerateData() method is called.
     *          After all the threads have completed, the AfterThreadedGenerateData() method is called.

```
would also be part of that class documentation.

- Template parameters are usually described in the class documentation, and hence, we save typing the same information for each class method.
- The type or variable returned, if necessary, is described in the method documentation, without the `\return` markup. 

- The authors and reference to the IJ paper is usually put once in the class documentation.

- No need to set the date systematically.

- Please, implement the `PrintSelf` method (i.e. print all member variables) as the last method of the implementation file.

- Use

`ITK_DISALLOW_COPY_AND_ASSIGN(TBBImageToImageFilter);`
to replace
 ```
TBBImageToImageFilter(const Self &); //purposely not implemented
void operator=(const Self &); //purposely not implemented
```
for the sake of consistency across the toolkit. 

[1] https://itk.org/Wiki/ITK/Coding_Style_Guide

**Comment by jhlegarreta** [comment]
@rdebroiz  Thanks. It's a lot more ITK stylish now !!

Please, check  the `README` for the _artical_ typo, as well as the class doc in the header.

A few comments:

- You'd use the **ITK macros** for the Get/Set functions. So you'd substitute
```c++

/** Gets the number of dimension to separate for the Jobs multithreading */
  unsigned int    GetNbReduceDimensions() const;

  /** Set the number of dimension to separate and multithread each section.
   * (nbReduceDim < 0  : negative number for automatic splitting)
   * \example : for a 3D image (volume) with the shape 30x10x5
   * nbReduceDim == 0  : Will generate a single (1) Job with the whole image (size 30x10x5)
   * nbReduceDim == 1  : Will generate 5 Jobs with the slices (size 30x10)
   * nbReduceDim == 2  : Will generate 50 Jobs with the lines (size 30)
   * nbReduceDim == 3  : Will generate 1500 Jobs with each voxel (size 1) */
  void            SetNbReduceDimensions(int);


/** Gets the number of jobs. */
  unsigned int    GetNumberOfJobs() const;

  /** Sets the number of jobs (Internal). */
void SetNumberOfJobs(unsigned int)
```

for (renaming the members as appropriate)

```c++
  /** Set/Get the number of dimension to separate and multithread each section.
   * Set a negative number for automatic splitting.
   * \example : for a 3D image (volume) with the shape 30x10x5
   * nbReduceDim == 0  : Will generate a single (1) Job with the whole image (size 30x10x5)
   * nbReduceDim == 1  : Will generate 5 Jobs with the slices (size 30x10)
   * nbReduceDim == 2  : Will generate 50 Jobs with the lines (size 30)
   * nbReduceDim == 3  : Will generate 1500 Jobs with each voxel (size 1) */
  itkSetMacro( NbReduceDimensions, int );
  
   /** Set/Get the number of jobs. */
  itkGetMacro( NumberOfJobs, unsigned int );
  itkSetMacro( NumberOfJobs, unsigned int );
```
  
I hesistate whether to substitute 
` itkGetMacro( NbReduceDimensions, unsigned int );`

since you are declaring the function as const; I've never seen an itkGetMacro with const modifier/ignore whether that would be compiled.

Also, I'd rename the variables and remove the **TBB** part; I haven't seen that the parent class has members having these types. And if the parent had them, why not use them?

Rename also `m_NbReduceDimensions` to a more meaningful/self-descriptive name, please. And do it accordingly for the example (`nbReduceDim`) given in the method doc.

Check the `itk::ProcessObject` and `itk::MultiThreader` to see how they declare the type of the number of threads/jobs. A typedef would may be welcome.


- You'd tipically mention the template parameters in the class doc as text, e.g. "This filter is templated over the input and output image types." So the syntax `\tparam` is not that common/used in ITK.

- Member variables are typically at the end, so you'd move the `ITK_DISALLOW_COPY_AND_ASSIGN` to the top of the private members or create a new private section just for it.

- Document `ResetJobQueue`, even if it is evident what it does. It may do more things that may be worthwhile to describe.

**Comment by rdebroiz** [comment]
>Also, I'd rename the variables and remove the TBB part; I haven't seen that the parent class has members having these types. And if the parent had them, why not use them?

I am not the author of the filter (i will try to contact them when there'll be available), but i think the reason why there is a new explicit `m_TBBNumberOfThreads` member instead of reusing the one from the inherited class `ProcessObject`, was probably to ensure that it is not modified else where in the code of `ProcessObject`. 
for instance, the setter for this member is: 
```c++
itkSetClampMacro(NumberOfThreads, ThreadIdType, 1, ITK_MAX_THREADS)
```
 where `ITK_MAX_THREADS` is system wise determined. The idea is now to let TBB manage those kind of things.

**Comment by rdebroiz** [comment]
i just commit: 
```
STYLE: Use ITK macro, and renaming.
NbJobs -> NumberOfJobs, use itkGetConstMacro and itkSetMacro
NbReduceDimensions -> NuumberOfDimensionToReduce use itkGetConstMacro
Add typedf JobIdType and DimensionReductionType
move ITK_DISALLOW_COPY_AND_ASSIGN at the top of the private section
correct typo: artical -> article
```

**Comment by jhlegarreta** [comment]
Although you could declare another variable named `m_NumberOfThreads` for the child, and use it without concerns about shadowing the parent variable, since it is private, an hence not directly accessible for the child, I guess we can leave it as it is for now. 
Thanks.

**Comment by jhlegarreta** [comment]
Virtually all comments were addressed in successive commits. Thanks.
